//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTeam14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int ID { get; set; }
        public string maTicket { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Dữ liệu không chứa khoảng trắng")]
        public string tenTicket { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Dữ liệu không chứa khoảng trắng")]
        public string ndTicket { get; set; }
        public string trangthai { get; set; }
        public Nullable<int> ID_vande { get; set; }
        public string admin { get; set; }
        public string nguoigui { get; set; }
    
        public virtual vande vande { get; set; }
    }
}
