//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTeam14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hocKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hocKy()
        {
            this.TKBs = new HashSet<TKB>();
        }

        public int ID { get; set; }
        [RegularExpression(@"^([^\s]*[A-Za-z0-9]\s{0,1})[^\s]*$", ErrorMessage = "Dữ liệu không có khoảng trắng")]

        public string tenHK { get; set; }
        [RegularExpression("^[0-9]*$", ErrorMessage = "Dữ liệu chỉ chấp nhận số")]
        public string namBD { get; set; }
        [RegularExpression("^[0-9]*$", ErrorMessage = "Dữ liệu chỉ chấp nhận số")]
        public string namKT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKB> TKBs { get; set; }
    }
}
