//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTeam14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class monHoc
    {
        public int ID { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Mã môn không chứa khoảng trắng")]
        public string maMon { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Tên môn không chứa khoảng trắng")]
        public string tenMon { get; set; }
        public Nullable<int> tinChi { get; set; }
        public string tengoiKhac { get; set; }
        public Nullable<int> ID_nguoiDung { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public Nullable<int> ID_phongHoc { get; set; }
        public Nullable<int> ID_hocPhan { get; set; }
    
        public virtual nguoiDung nguoiDung { get; set; }
    }
}
