//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTeam14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Nganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nganh()
        {
            this.hocKies = new HashSet<hocKy>();
            this.TKBs = new HashSet<TKB>();
        }
    
        public int ID { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Mã ngành không chứa khoảng trắng")]
        public string maNganh { get; set; }
        [RegularExpression(@"^\S+(?:\s\S+)*$", ErrorMessage = "Tên ngành không chứa khoảng trắng")]
        public string tenNganh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hocKy> hocKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKB> TKBs { get; set; }
    }
}
