//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTeam14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKB
    {
        public int ID { get; set; }
        public Nullable<int> ID_hocPhan { get; set; }
        public Nullable<int> ID_monHoc { get; set; }
        public Nullable<int> ID_Lop { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public Nullable<int> ID_Tuan { get; set; }
        public Nullable<int> ID_Tiet { get; set; }
        public Nullable<int> ID_GV { get; set; }
    
        public virtual hocPhan hocPhan { get; set; }
        public virtual lopHoc lopHoc { get; set; }
        public virtual monHoc monHoc { get; set; }
        public virtual Nganh Nganh { get; set; }
        public virtual nguoiDung nguoiDung { get; set; }
        public virtual phongHoc phongHoc { get; set; }
        public virtual tietHoc tietHoc { get; set; }
        public virtual tuanHoc tuanHoc { get; set; }
    }
}
